### PR TITLE
add afterFilterCallback

### PR DESCRIPTION
**Pull request by wenjiechen**
1 when filter data, this callback will be invoked.
2 fixed:  currentFilters didn't update after remove all filters. this is because setState() has a pending state, which won't change currentFilters immediately

### CODE REVIEW

**Comment by wenjiechen** [comment]
when add filter or delete filter, afterFilterCallback will be invoked

**Comment by wenjiechen** [comment]
add null check for afterFilterCallback

**Comment by wenjiechen** [comment]
1 when add sort or filter icon in a column, the width of the column should be expanded accordingly.
2 when scroll table horizontally, filter panel should be relocated in right position.
3 remove jquery selector with react refs property. refs should be faster than jquery selector.

**Comment by wenjiechen** [comment]
move grand total row to the bottom of the table, and make it fixed.

**Comment by erfangc** [comment]
Is this toggable?

**Comment by wenjiechen** [comment]
yes, the grand total has the same functionality as before

**Pull request merged**
