### PR TITLE
customize the right click menu items for each column

### PR DESCRIPTION
**Pull request by wenjiechen**

### CODE REVIEW

**Comment by erfangc** [comment]
If there are features you want. Can you add them as issues in GigaGrid as
well.

**Comment by erfangc** [comment]
It looks like there are merge conflicts can you resolve them

**Comment by erfangc** [comment]
I manually merged your fork **locally**, can I push it up to your fork? (i.e. add me as collaborator to your fork)

**Comment by wenjiechen** [comment]
ok no problem. This feature is added by another contributor, who is in blk as well. 

Wenjie Chen

**Comment by erfangc** [comment]
@wenjiechen thanks, did you give me perms? I am still getting:

```bash
git push -u wenjiechen master
remote: Permission to wenjiechen/ReactTable.git denied to erfangc.
fatal: unable to access 'https://github.com/wenjiechen/ReactTable.git/': The requested URL returned error: 403
```

**Comment by wenjiechen** [comment]
Yes, I just did. Thanks.

**Pull request merged**
